export const APP1_ROLES = Object.freeze({
  ADM: "ADM",
  DEV: "DEV"
});

export const ACCOUNT_STATUS = Object.freeze({
  ACTIVE: "ACTIVE",
  SUSPENDED: "SUSPENDED",
  DELETED: "DELETED"
});

export const KEYMASTER = Object.freeze({
  MAX_KEY_CHARS: 16384,
  DEFAULT_ACCESS_KEY_CHARS: 5000,
  MAX_FAILED_ATTEMPTS: 3,
  LOCK_HOURS: 24,
  CRITICAL_AUTH_MINUTES: 2
});

export const CRITICAL_ACTIONS = Object.freeze({
  APP1_RESTART: "APP1_RESTART",
  APP1_MAINTENANCE_ON: "APP1_MAINTENANCE_ON",
  APP1_MAINTENANCE_OFF: "APP1_MAINTENANCE_OFF",
  DELETE_APP1_ACCOUNT: "DELETE_APP1_ACCOUNT"
});

export const API_ERRORS = Object.freeze({
  INVALID_CREDENTIAL: "INVALID_CREDENTIAL",
  DEVICE_LOCKED: "DEVICE_LOCKED",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  ACCOUNT_DELETED: "ACCOUNT_DELETED",
  APP1_MAINTENANCE: "APP1_MAINTENANCE",
  DEV_REAUTH_REQUIRED: "DEV_REAUTH_REQUIRED",
  INVALID_DEV_CREDENTIAL: "INVALID_DEV_CREDENTIAL",
  CRITICAL_AUTH_INVALID: "CRITICAL_AUTH_INVALID",
  FORBIDDEN: "FORBIDDEN",
  UNAUTHORIZED: "UNAUTHORIZED",
  INTEGRITY_REQUIRED: "INTEGRITY_REQUIRED"
});
