export const APP1_ROLES = Object.freeze({
  ADM: "ADM",
  DEV: "DEV"
});

export const ACCOUNT_STATUS = Object.freeze({
  ACTIVE: "ACTIVE",
  LOCKED_SECURITY: "LOCKED_SECURITY",
  SUSPENDED: "SUSPENDED",
  DELETED: "DELETED"
});

export const APP1_CREDENTIAL_POLICY = Object.freeze({
  ADM_CHARS: 256,
  DEV_CHARS: 600,
  SESSION_HOURS: 24
});

export const APP1_PERMISSIONS = Object.freeze({
  SESSION_USE: "app1.session.use",
  ADMIN_AREA: "app1.admin",
  DEV_PRIVILEGED: "app1.dev.privileged",
  SOCIAL_PIN_POST: "app1.social.pin-post"
});

export const APP1_ROLE_PERMISSIONS = Object.freeze({
  [APP1_ROLES.ADM]: Object.freeze([
    APP1_PERMISSIONS.SESSION_USE,
    APP1_PERMISSIONS.ADMIN_AREA
  ]),
  [APP1_ROLES.DEV]: Object.freeze([
    APP1_PERMISSIONS.SESSION_USE,
    APP1_PERMISSIONS.ADMIN_AREA,
    APP1_PERMISSIONS.DEV_PRIVILEGED,
    APP1_PERMISSIONS.SOCIAL_PIN_POST
  ])
});

export function permissionsForRole(role) {
  const normalized = String(role || "").toUpperCase();
  return APP1_ROLE_PERMISSIONS[normalized] || Object.freeze([]);
}

export function roleHasPermission(role, permission) {
  return permissionsForRole(role).includes(String(permission || ""));
}

export const KEYMASTER = Object.freeze({
  MAX_KEY_CHARS: 16384,
  DEFAULT_ACCESS_KEY_CHARS: 5000,
  MAX_FAILED_ATTEMPTS: 3,
  LOCK_HOURS: 24,
  CRITICAL_AUTH_MINUTES: 2
});

export const CRITICAL_ACTIONS = Object.freeze({
  APP1_RESTART: "APP1_RESTART",
  APP1_MAINTENANCE_ON: "APP1_MAINTENANCE_ON",
  APP1_MAINTENANCE_OFF: "APP1_MAINTENANCE_OFF",
  DELETE_APP1_ACCOUNT: "DELETE_APP1_ACCOUNT",
  DELETE_MANAGED_MENU: "DELETE_MANAGED_MENU",
  UNLOCK_APP1_ACCOUNT: "UNLOCK_APP1_ACCOUNT",
  AUTHORIZE_APP1_DEVICE: "AUTHORIZE_APP1_DEVICE",
  REVOKE_APP1_DEVICE: "REVOKE_APP1_DEVICE",
  ROTATE_APP1_CREDENTIAL: "ROTATE_APP1_CREDENTIAL",
  REVEAL_APP1_CREDENTIAL: "REVEAL_APP1_CREDENTIAL"
});

export const API_ERRORS = Object.freeze({
  INVALID_CREDENTIAL: "INVALID_CREDENTIAL",
  DEVICE_LOCKED: "DEVICE_LOCKED",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  ACCOUNT_DELETED: "ACCOUNT_DELETED",
  APP1_MAINTENANCE: "APP1_MAINTENANCE",
  DEV_REAUTH_REQUIRED: "DEV_REAUTH_REQUIRED",
  INVALID_DEV_CREDENTIAL: "INVALID_DEV_CREDENTIAL",
  CRITICAL_AUTH_INVALID: "CRITICAL_AUTH_INVALID",
  FORBIDDEN: "FORBIDDEN",
  UNAUTHORIZED: "UNAUTHORIZED",
  INTEGRITY_REQUIRED: "INTEGRITY_REQUIRED"
});
