import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#030303" },
  center: { flex: 1, alignItems: "center", justifyContent: "center", padding: 20 },
  page: { padding: 20, paddingBottom: 50 },
  pageFlex: { flex: 1, padding: 20 },
  loginBrand: { alignItems: "center", marginBottom: 28 },
  brand: { color: "#FFFFFF", fontSize: 50, fontFamily: Platform.select({ ios: "Georgia", android: "serif" }), letterSpacing: 0.5 },
  loginSubtitle: { color: "#7F7F7F", fontSize: 14, marginTop: 4, letterSpacing: 0.6 },
  loginBox: { width: "100%", maxWidth: 520, padding: 22, borderRadius: 22, borderWidth: 1, borderColor: "#303030", backgroundColor: "#090909" },
  eyebrow: { color: "#777", fontSize: 10, letterSpacing: 2.1, fontWeight: "800" },
  headerTitle: { color: "#FFFFFF", fontSize: 18, fontWeight: "900", marginTop: 1, letterSpacing: 0.6 },
  screenTitle: { color: "#FFFFFF", fontSize: 27, fontWeight: "900", marginTop: 22 },
  muted: { color: "#929292", fontSize: 14, lineHeight: 20, marginTop: 6 },
  small: { color: "#6F6F6F", fontSize: 11, marginTop: 8 },
  labelRow: { marginTop: 4, flexDirection: "row", justifyContent: "space-between", gap: 10 },
  label: { color: "#D6D6D6", fontSize: 11, fontWeight: "800" },
  counter: { color: "#707070", fontSize: 11 },
  input: { backgroundColor: "#111", color: "#FFF", borderWidth: 1, borderColor: "#303030", borderRadius: 14, paddingHorizontal: 14, minHeight: 52, marginTop: 10, fontSize: 15 },
  rowGap: { flexDirection: "row", gap: 9, marginTop: 10 },
  halfButton: { flex: 1, borderWidth: 1, borderColor: "#2A2A2A", borderRadius: 12, paddingVertical: 11, alignItems: "center", backgroundColor: "#0E0E0E" },
  halfButtonText: { color: "#D8D8D8", fontWeight: "800", fontSize: 12 },
  selected: { borderColor: "#FFFFFF" },
  selectedDev: { borderColor: "#FF3B30", backgroundColor: "#180909" },
  button: { marginTop: 14, borderRadius: 14, backgroundColor: "#FFFFFF", minHeight: 50, alignItems: "center", justifyContent: "center", paddingHorizontal: 16 },
  buttonSecondary: { backgroundColor: "#101010", borderWidth: 1, borderColor: "#2A2A2A" },
  buttonDanger: { backgroundColor: "#D51E2A" },
  buttonMuted: { opacity: 0.52 },
  buttonText: { color: "#050505", fontWeight: "900", fontSize: 13, letterSpacing: 0.3 },
  buttonTextSecondary: { color: "#FFFFFF" },
  buttonTextDanger: { color: "#FFFFFF" },
  privacy: { color: "#636363", fontSize: 11, lineHeight: 16, textAlign: "center", marginTop: 16 },
  error: { color: "#FF453A", fontSize: 13, marginTop: 12, lineHeight: 18 },
  topRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", minHeight: 46 },
  headerSide: { width: 80 },
  headerRight: { alignItems: "flex-end" },
  headerCenter: { flex: 1, alignItems: "center" },
  link: { color: "#FFFFFF", fontWeight: "700", paddingVertical: 8, fontSize: 13 },
  securityCard: { marginTop: 22, borderRadius: 18, padding: 17, borderWidth: 1, borderColor: "#1E3A27", backgroundColor: "#07100A" },
  criticalSecurity: { borderColor: "#442020", backgroundColor: "#120707" },
  securityTitle: { color: "#E5FFE9", fontWeight: "800", fontSize: 15 },
  statusLine: { flexDirection: "row", alignItems: "center", gap: 9 },
  greenDot: { width: 9, height: 9, borderRadius: 99, backgroundColor: "#37D85B" },
  redDot: { width: 9, height: 9, borderRadius: 99, backgroundColor: "#FF3B30" },
  section: { color: "#666", fontWeight: "800", fontSize: 10, letterSpacing: 1.5, marginTop: 28, marginBottom: 10 },
  card: { borderRadius: 18, borderWidth: 1, borderColor: "#242424", backgroundColor: "#0A0A0A", padding: 17, position: "relative" },
  criticalCard: { borderColor: "#4A1717" },
  lockedCard: { borderColor: "#3A1111" },
  cardTitle: { color: "#FFF", fontWeight: "800", fontSize: 16 },
  cardArrow: { position: "absolute", right: 17, top: 18, color: "#777", fontSize: 28 },
  criticalLabel: { color: "#FF453A", fontWeight: "900", fontSize: 10, marginTop: 13, letterSpacing: 0.5 },
  locked: { color: "#FF453A", fontWeight: "800", fontSize: 10, marginTop: 14 },
  summaryGrid: { flexDirection: "row", gap: 10, marginTop: 12 },
  summaryCard: { flex: 1, borderRadius: 15, backgroundColor: "#0A0A0A", borderWidth: 1, borderColor: "#222", padding: 14 },
  summaryLabel: { color: "#666", fontWeight: "800", fontSize: 9, letterSpacing: 1.2 },
  summaryValue: { color: "#FFF", fontWeight: "900", fontSize: 13, marginTop: 6 },
  greenText: { color: "#55E27D" },
  redText: { color: "#FF453A" },
  listHeader: { flexDirection: "row", alignItems: "flex-end", gap: 14 },
  addButton: { width: 48, height: 48, borderRadius: 14, borderWidth: 1, borderColor: "#333", alignItems: "center", justifyContent: "center", marginLeft: "auto" },
  add: { color: "#FFFFFF", fontSize: 29, lineHeight: 30 },
  accountCard: { padding: 15, borderRadius: 16, borderWidth: 1, borderColor: "#222", marginBottom: 11, backgroundColor: "#090909" },
  accountTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" },
  badge: { color: "#D8D8D8", fontSize: 10, fontWeight: "900", marginTop: 7 },
  badgeDev: { color: "#FF453A" },
  active: { color: "#55E27D", fontSize: 10, fontWeight: "900" },
  suspended: { color: "#FF9F0A", fontSize: 10, fontWeight: "900" },
  smallAction: { flex: 1, borderWidth: 1, borderColor: "#2A2A2A", borderRadius: 10, paddingVertical: 10, alignItems: "center" },
  smallActionText: { color: "#DADADA", fontSize: 9, fontWeight: "900" },
  smallDanger: { borderColor: "#4A1B1B", backgroundColor: "#140707" },
  smallDangerText: { color: "#FF453A", fontSize: 9, fontWeight: "900" },
  empty: { color: "#666", textAlign: "center", marginTop: 40 },
  modalBackdrop: { flex: 1, backgroundColor: "rgba(0,0,0,0.86)", justifyContent: "center", padding: 20 },
  modalBox: { backgroundColor: "#090909", borderRadius: 20, borderWidth: 1, borderColor: "#303030", padding: 20, maxHeight: "86%" },
  devModal: { borderColor: "#542020" },
  devTag: { color: "#FF453A", fontSize: 10, fontWeight: "900", letterSpacing: 0.8, marginBottom: 10 },
  warning: { color: "#FF9F0A", fontSize: 11, fontWeight: "900", marginTop: 10 },
  credentialBox: { maxHeight: 190, marginTop: 14, backgroundColor: "#050505", borderWidth: 1, borderColor: "#252525", borderRadius: 12, padding: 12 },
  credentialText: { color: "#DADADA", fontFamily: Platform.select({ ios: "Menlo", android: "monospace" }), fontSize: 11, lineHeight: 17 },
  cardStack: { gap: 10 },
  actionCard: { borderRadius: 17, borderWidth: 1, borderColor: "#272727", backgroundColor: "#0A0A0A", padding: 16, flexDirection: "row", alignItems: "center", gap: 12 },
  actionPill: { minWidth: 88, borderRadius: 11, paddingHorizontal: 12, paddingVertical: 11, alignItems: "center" },
  actionPillDanger: { backgroundColor: "#B71922" },
  actionPillSafe: { backgroundColor: "#144921" },
  actionPillText: { color: "#FFF", fontWeight: "900", fontSize: 9 }
});
