import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#030303" },
  center: { flex: 1, alignItems: "center", justifyContent: "center", padding: 20 },
  screenShell: { flex: 1 },
  screenBody: { flex: 1, paddingHorizontal: 18, paddingTop: 12 },
  page: { padding: 20, paddingBottom: 50 },
  pageWithNav: { paddingHorizontal: 18, paddingTop: 12, paddingBottom: 34 },
  pageFlex: { flex: 1, padding: 20 },
  loginBrand: { alignItems: "center", marginBottom: 28 },
  brand: { color: "#FFFFFF", fontSize: 50, fontFamily: Platform.select({ ios: "Georgia", android: "serif" }), letterSpacing: 0.5 },
  loginSubtitle: { color: "#7F7F7F", fontSize: 14, marginTop: 4, letterSpacing: 0.6 },
  loginBox: { width: "100%", maxWidth: 520, padding: 22, borderRadius: 22, borderWidth: 1, borderColor: "#303030", backgroundColor: "#090909" },
  eyebrow: { color: "#777", fontSize: 10, letterSpacing: 2.1, fontWeight: "800" },
  headerTitle: { color: "#FFFFFF", fontSize: 18, fontWeight: "900", marginTop: 1, letterSpacing: 0.6 },
  screenTitle: { color: "#FFFFFF", fontSize: 28, fontWeight: "900", marginTop: 18, letterSpacing: -0.6 },
  muted: { color: "#929298", fontSize: 14, lineHeight: 20, marginTop: 6 },
  small: { color: "#6F6F75", fontSize: 11, marginTop: 8 },
  labelRow: { marginTop: 4, flexDirection: "row", justifyContent: "space-between", gap: 10 },
  label: { color: "#D6D6D6", fontSize: 11, fontWeight: "800" },
  counter: { color: "#707070", fontSize: 11 },
  input: { backgroundColor: "#111", color: "#FFF", borderWidth: 1, borderColor: "#303030", borderRadius: 14, paddingHorizontal: 14, minHeight: 52, marginTop: 10, fontSize: 15 },
  searchInput: { backgroundColor: "#101014", color: "#FFF", borderWidth: 1, borderColor: "#25252B", borderRadius: 15, paddingHorizontal: 15, minHeight: 50, marginTop: 18, fontSize: 15 },
  rowGap: { flexDirection: "row", gap: 9, marginTop: 10 },
  halfButton: { flex: 1, borderWidth: 1, borderColor: "#2A2A2A", borderRadius: 12, paddingVertical: 11, alignItems: "center", backgroundColor: "#0E0E0E" },
  halfButtonText: { color: "#D8D8D8", fontWeight: "800", fontSize: 12 },
  selected: { borderColor: "#A66CFF", backgroundColor: "#130C1E" },
  selectedDev: { borderColor: "#FF3B30", backgroundColor: "#180909" },
  button: { marginTop: 14, borderRadius: 14, backgroundColor: "#FFFFFF", minHeight: 50, alignItems: "center", justifyContent: "center", paddingHorizontal: 16 },
  buttonSecondary: { backgroundColor: "#101010", borderWidth: 1, borderColor: "#2A2A2A" },
  buttonDanger: { backgroundColor: "#D51E2A" },
  buttonMuted: { opacity: 0.52 },
  buttonText: { color: "#050505", fontWeight: "900", fontSize: 13, letterSpacing: 0.3 },
  buttonTextSecondary: { color: "#FFFFFF" },
  buttonTextDanger: { color: "#FFFFFF" },
  privacy: { color: "#636363", fontSize: 11, lineHeight: 16, textAlign: "center", marginTop: 16 },
  error: { color: "#FF453A", fontSize: 13, marginTop: 12, lineHeight: 18 },
  topRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", minHeight: 46 },
  headerSide: { width: 80 },
  headerRight: { alignItems: "flex-end" },
  headerCenter: { flex: 1, alignItems: "center" },
  link: { color: "#FFFFFF", fontWeight: "700", paddingVertical: 8, fontSize: 13 },
  securityCard: { marginTop: 22, borderRadius: 18, padding: 17, borderWidth: 1, borderColor: "#1E3A27", backgroundColor: "#07100A" },
  criticalSecurity: { borderColor: "#442020", backgroundColor: "#120707" },
  securityTitle: { color: "#E8E8EA", fontWeight: "800", fontSize: 14 },
  statusLine: { flexDirection: "row", alignItems: "center", gap: 9, marginTop: 14 },
  greenDot: { width: 9, height: 9, borderRadius: 99, backgroundColor: "#37D85B" },
  redDot: { width: 9, height: 9, borderRadius: 99, backgroundColor: "#FF3B30" },
  section: { color: "#77777E", fontWeight: "900", fontSize: 10, letterSpacing: 1.5, marginTop: 28, marginBottom: 10 },
  sectionInline: { color: "#77777E", fontWeight: "900", fontSize: 10, letterSpacing: 1.2 },
  card: { borderRadius: 18, borderWidth: 1, borderColor: "#242424", backgroundColor: "#0A0A0A", padding: 17, position: "relative" },
  criticalCard: { borderColor: "#4A1717" },
  lockedCard: { borderColor: "#3A1111" },
  cardTitle: { color: "#FFF", fontWeight: "800", fontSize: 16 },
  cardArrow: { color: "#777", fontSize: 28, marginLeft: 8 },
  criticalLabel: { color: "#FF453A", fontWeight: "900", fontSize: 10, marginTop: 13, letterSpacing: 0.5 },
  locked: { color: "#FF453A", fontWeight: "800", fontSize: 10, marginTop: 14 },
  summaryGrid: { flexDirection: "row", gap: 10, marginTop: 12 },
  summaryCard: { flex: 1, borderRadius: 15, backgroundColor: "#0A0A0A", borderWidth: 1, borderColor: "#222", padding: 14 },
  summaryLabel: { color: "#666", fontWeight: "800", fontSize: 9, letterSpacing: 1.2 },
  summaryValue: { color: "#FFF", fontWeight: "900", fontSize: 13, marginTop: 6 },
  greenText: { color: "#55E27D" },
  redText: { color: "#FF453A" },

  heroCard: { marginTop: 18, borderRadius: 22, padding: 20, borderWidth: 1, borderColor: "#34204F", backgroundColor: "#0D0912" },
  heroBadge: { alignSelf: "flex-start", backgroundColor: "#20122F", borderWidth: 1, borderColor: "#6E3BA7", borderRadius: 9, paddingHorizontal: 10, paddingVertical: 5 },
  heroBadgeText: { color: "#BD83FF", fontSize: 9, fontWeight: "900", letterSpacing: 1.1 },
  heroTitle: { color: "#FFFFFF", fontSize: 30, fontWeight: "900", marginTop: 15, letterSpacing: 0.5 },
  heroSubtitle: { color: "#A2A2A8", fontSize: 13, marginTop: 3 },
  metricGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginTop: 12 },
  metricCard: { width: "48%", flexGrow: 1, minHeight: 92, borderRadius: 17, backgroundColor: "#0B0B0E", borderWidth: 1, borderColor: "#232329", padding: 15 },
  metricLabel: { color: "#77777E", fontWeight: "900", fontSize: 9, letterSpacing: 1.2 },
  metricValue: { color: "#FFFFFF", fontWeight: "900", fontSize: 20, marginTop: 8 },
  metricHint: { color: "#6F6F75", fontSize: 10, marginTop: 3 },
  featureCard: { borderRadius: 18, borderWidth: 1, borderColor: "#24242A", backgroundColor: "#0A0A0D", padding: 16, marginBottom: 10, flexDirection: "row", alignItems: "center", gap: 13 },
  featureIcon: { width: 42, height: 42, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "#17101F", borderWidth: 1, borderColor: "#432963" },
  featureIconDanger: { backgroundColor: "#180909", borderColor: "#572020" },
  featureIconText: { color: "#B875FF", fontSize: 20, fontWeight: "900" },

  listHeader: { flexDirection: "row", alignItems: "flex-end", gap: 14 },
  listHeaderCompact: { flexDirection: "row", alignItems: "flex-end", gap: 14 },
  addButton: { width: 48, height: 48, borderRadius: 14, borderWidth: 1, borderColor: "#6E3BA7", backgroundColor: "#17101F", alignItems: "center", justifyContent: "center", marginLeft: "auto" },
  add: { color: "#B875FF", fontSize: 29, lineHeight: 30 },
  iconAction: { width: 44, height: 44, borderRadius: 13, borderWidth: 1, borderColor: "#333", alignItems: "center", justifyContent: "center" },
  iconActionText: { color: "#D9D9DD", fontSize: 20, fontWeight: "800" },
  filterRow: { gap: 8, paddingVertical: 12, paddingRight: 14 },
  filterChip: { borderRadius: 999, borderWidth: 1, borderColor: "#29292F", backgroundColor: "#0D0D10", paddingHorizontal: 13, paddingVertical: 8 },
  filterChipActive: { borderColor: "#8951C8", backgroundColor: "#1B1027" },
  filterChipDev: { borderColor: "#A52C32", backgroundColor: "#220B0D" },
  filterChipText: { color: "#8C8C93", fontSize: 10, fontWeight: "900" },
  filterChipTextActive: { color: "#FFFFFF" },
  filterDivider: { width: 1, height: 28, backgroundColor: "#24242A", marginHorizontal: 3, alignSelf: "center" },
  accountList: { paddingTop: 2, paddingBottom: 28 },
  accountCard: { padding: 15, borderRadius: 17, borderWidth: 1, borderColor: "#24242A", marginBottom: 11, backgroundColor: "#09090C" },
  accountTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: 12 },
  accountTitleRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  accountMeta: { color: "#6E6E75", fontSize: 10, lineHeight: 15, marginTop: 7 },
  badge: { color: "#B875FF", fontSize: 9, fontWeight: "900", backgroundColor: "#1B1027", borderRadius: 7, paddingHorizontal: 7, paddingVertical: 3 },
  badgeDev: { color: "#FF5A52", backgroundColor: "#210A0C" },
  active: { color: "#55E27D", fontSize: 10, fontWeight: "900" },
  suspended: { color: "#FF9F0A", fontSize: 10, fontWeight: "900" },
  sessionOff: { color: "#77777E", fontSize: 9, fontWeight: "900", marginLeft: 8 },
  smallAction: { flex: 1, borderWidth: 1, borderColor: "#2A2A2F", borderRadius: 10, paddingVertical: 10, alignItems: "center" },
  smallActionText: { color: "#DADADD", fontSize: 9, fontWeight: "900" },
  smallDanger: { borderColor: "#4A1B1B", backgroundColor: "#140707" },
  smallDangerText: { color: "#FF453A", fontSize: 9, fontWeight: "900" },
  empty: { color: "#666", textAlign: "center", marginTop: 40 },
  emptyCompact: { color: "#666", textAlign: "center", paddingVertical: 24 },

  modalBackdrop: { flex: 1, backgroundColor: "rgba(0,0,0,0.88)", justifyContent: "center", padding: 18 },
  modalBox: { backgroundColor: "#09090C", borderRadius: 22, borderWidth: 1, borderColor: "#303036", padding: 20, maxHeight: "88%" },
  detailModal: { minHeight: "55%" },
  detailHeader: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  closeText: { color: "#A0A0A7", fontSize: 20, paddingHorizontal: 6 },
  detailGrid: { flexDirection: "row", gap: 9, marginTop: 18 },
  detailCell: { flex: 1, borderRadius: 13, backgroundColor: "#101014", borderWidth: 1, borderColor: "#25252B", padding: 12 },
  detailLabel: { color: "#68686F", fontSize: 8, fontWeight: "900", letterSpacing: 1 },
  detailValue: { color: "#D7D7DC", fontSize: 10, marginTop: 6, lineHeight: 14 },
  detailSectionRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 20, marginBottom: 8 },
  refreshLink: { color: "#B875FF", fontWeight: "900", fontSize: 9 },
  sessionsList: { maxHeight: 300 },
  sessionCard: { borderRadius: 13, borderWidth: 1, borderColor: "#25252B", padding: 12, marginBottom: 8, flexDirection: "row", alignItems: "center", gap: 8 },
  sessionTitle: { color: "#E8E8EC", fontWeight: "800", fontSize: 12 },
  revokeButton: { borderRadius: 9, borderWidth: 1, borderColor: "#542020", backgroundColor: "#160809", paddingHorizontal: 9, paddingVertical: 8 },
  revokeButtonText: { color: "#FF5148", fontWeight: "900", fontSize: 8 },
  devModal: { borderColor: "#542020" },
  devTag: { color: "#FF453A", fontSize: 10, fontWeight: "900", letterSpacing: 0.8, marginBottom: 10 },
  warning: { color: "#FF9F0A", fontSize: 11, fontWeight: "900", marginTop: 10 },
  credentialBox: { maxHeight: 190, marginTop: 14, backgroundColor: "#050505", borderWidth: 1, borderColor: "#252525", borderRadius: 12, padding: 12 },
  credentialText: { color: "#DADADA", fontFamily: Platform.select({ ios: "Menlo", android: "monospace" }), fontSize: 11, lineHeight: 17 },

  auditList: { paddingTop: 16, paddingBottom: 28 },
  auditCard: { borderRadius: 16, borderWidth: 1, borderColor: "#25252B", backgroundColor: "#0A0A0D", padding: 14, marginBottom: 9 },
  auditCardDev: { borderColor: "#4C2020" },
  auditTop: { flexDirection: "row", alignItems: "center", gap: 8 },
  auditDot: { width: 7, height: 7, borderRadius: 99, backgroundColor: "#A66CFF" },
  auditDotDev: { backgroundColor: "#FF453A" },
  auditTitle: { color: "#EEEEF2", fontWeight: "800", fontSize: 12, flex: 1 },
  auditTime: { color: "#65656C", fontSize: 8 },
  auditMeta: { color: "#77777E", fontSize: 10, marginTop: 8, lineHeight: 15 },
  auditDanger: { color: "#FF5148", fontWeight: "800", fontSize: 9, marginTop: 8 },
  loadMore: { borderRadius: 13, borderWidth: 1, borderColor: "#303036", paddingVertical: 12, alignItems: "center", marginTop: 5 },
  loadMoreText: { color: "#B875FF", fontSize: 9, fontWeight: "900" },

  cardStack: { gap: 10 },
  actionCard: { borderRadius: 17, borderWidth: 1, borderColor: "#272727", backgroundColor: "#0A0A0A", padding: 16, flexDirection: "row", alignItems: "center", gap: 12 },
  actionPill: { minWidth: 88, borderRadius: 11, paddingHorizontal: 12, paddingVertical: 11, alignItems: "center" },
  actionPillDanger: { backgroundColor: "#B71922" },
  actionPillSafe: { backgroundColor: "#144921" },
  actionPillText: { color: "#FFF", fontWeight: "900", fontSize: 9 },

  bottomNav: { minHeight: 72, borderTopWidth: 1, borderTopColor: "#202024", backgroundColor: "#050506", flexDirection: "row", alignItems: "center", paddingHorizontal: 8, paddingTop: 7, paddingBottom: Platform.OS === "ios" ? 10 : 7 },
  bottomNavItem: { flex: 1, alignItems: "center", justifyContent: "center" },
  bottomNavIcon: { width: 31, height: 28, borderRadius: 9, alignItems: "center", justifyContent: "center" },
  bottomNavIconActive: { backgroundColor: "#1B1027" },
  bottomNavIconDanger: { backgroundColor: "#21090B" },
  bottomNavIconText: { color: "#77777E", fontSize: 17, fontWeight: "900" },
  bottomNavLabel: { color: "#717178", fontSize: 9, fontWeight: "700", marginTop: 2 },
  bottomNavTextActive: { color: "#B875FF" }
});
