package com.cafeina.executor;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.res.ColorStateList;
import android.graphics.Color;
import android.graphics.Typeface;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;

import org.json.JSONArray;
import org.json.JSONObject;

import java.text.DateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/**
 * Read-only reports generated by the deterministic laboratory test agent.
 */
public final class LaboratoryAiTestAgentReportsActivity extends Activity {
    private static final int BG = Color.rgb(12, 13, 16);
    private static final int FG = Color.rgb(240, 242, 247);
    private static final int MUTED = Color.rgb(170, 177, 192);
    private static final int PANEL = Color.rgb(36, 41, 52);
    private static final int ACCENT = Color.rgb(59, 139, 254);

    private final ExecutorService io = Executors.newSingleThreadExecutor();
    private LaboratoryAiTestAgentReportStore store;
    private TextView feedback;
    private LinearLayout entries;

    @Override
    protected void onCreate(Bundle state) {
        super.onCreate(state);
        getWindow().setStatusBarColor(BG);
        getWindow().setNavigationBarColor(BG);

        LinearLayout root = new LinearLayout(this);
        root.setOrientation(LinearLayout.VERTICAL);
        root.setPadding(dp(16), dp(14), dp(16), dp(14));
        root.setBackgroundColor(BG);
        setContentView(root);

        Button back = button("← VOLTAR");
        back.setOnClickListener(v -> finish());
        root.addView(back, matchWrap());

        TextView title = text("IA DE TESTE • RELATÓRIOS", 20, FG, true);
        title.setPadding(0, dp(16), 0, dp(6));
        root.addView(title, matchWrap());

        root.addView(text(
            "Agente determinístico do laboratório. Os relatórios não armazenam "
                + "tool_input, retorno, stdout ou erros brutos; somente hashes e evidências.",
            14, MUTED, false), matchWrap());

        feedback = text("Carregando relatórios…", 14, MUTED, false);
        feedback.setPadding(0, dp(12), 0, dp(8));
        root.addView(feedback, matchWrap());

        ScrollView scroll = new ScrollView(this);
        entries = new LinearLayout(this);
        entries.setOrientation(LinearLayout.VERTICAL);
        scroll.addView(entries);
        root.addView(scroll, new LinearLayout.LayoutParams(
            ViewGroup.LayoutParams.MATCH_PARENT, 0, 1f));

        String projectId = getSharedPreferences("cafeina_workspace", MODE_PRIVATE)
            .getString("project_id", "");
        store = new LaboratoryAiTestAgentReportStore(getFilesDir(), projectId);
        refresh();
    }

    @Override
    protected void onResume() {
        super.onResume();
        if (store != null) refresh();
    }

    private void refresh() {
        io.execute(() -> {
            try {
                List<LaboratoryAiTestAgentReportStore.Entry> reports = store.list();
                runOnUiThread(() -> render(reports));
            } catch (Exception error) {
                runOnUiThread(() -> {
                    if (alive()) feedback.setText(
                        "Falha ao ler relatórios: " + error.getMessage());
                });
            }
        });
    }

    private void render(List<LaboratoryAiTestAgentReportStore.Entry> reports) {
        if (!alive()) return;
        entries.removeAllViews();
        feedback.setText(reports.size() + " relatório(s) da IA de teste");

        if (reports.isEmpty()) {
            entries.addView(text(
                "Nenhuma execução da IA de teste foi registrada.",
                14, MUTED, false), matchWrap());
            return;
        }

        for (LaboratoryAiTestAgentReportStore.Entry report : reports) {
            Button item = button(
                report.status + " • " + report.passed + " passou / "
                    + report.failed + " falhou\n"
                    + time(report.startedAtEpochMs)
                    + "  |  " + report.executedSteps + "/"
                    + report.plannedSteps + " passos");
            item.setAllCaps(false);
            item.setGravity(android.view.Gravity.START
                | android.view.Gravity.CENTER_VERTICAL);
            item.setBackgroundTintList(ColorStateList.valueOf(PANEL));
            item.setOnClickListener(v -> showReport(report));
            LinearLayout.LayoutParams params = matchWrap();
            params.setMargins(0, dp(8), 0, 0);
            entries.addView(item, params);
        }
    }

    private void showReport(LaboratoryAiTestAgentReportStore.Entry entry) {
        io.execute(() -> {
            try {
                String raw = store.read(entry.reportId);
                JSONObject json = new JSONObject(raw);
                StringBuilder body = new StringBuilder()
                    .append("Relatório: ").append(entry.reportId)
                    .append("\nContrato: ").append(json.optString("contractId"))
                    .append("\nGoal SHA-256: ").append(json.optString("goalSha256"))
                    .append("\nModo: ").append(json.optString("mode"))
                    .append("\nSessão: ")
                    .append(json.optString("sessionId").isEmpty()
                        ? "nenhuma" : json.optString("sessionId"))
                    .append("\nStatus: ").append(json.optString("status"))
                    .append("\nMotivo terminal: ")
                    .append(json.optString("terminalReason").isEmpty()
                        ? "—" : json.optString("terminalReason"))
                    .append("\nInício: ")
                    .append(time(json.optLong("startedAtEpochMs")))
                    .append("\nDuração: ").append(json.optLong("durationMs"))
                    .append(" ms")
                    .append("\nPassos: ").append(json.optInt("executedSteps"))
                    .append(" / ").append(json.optInt("plannedSteps"))
                    .append("\nPASS: ").append(json.optInt("passed"))
                    .append(" • FAIL: ").append(json.optInt("failed"))
                    .append("\nStop on failure: ")
                    .append(json.optBoolean("stopOnFailure") ? "SIM" : "NÃO");

                JSONArray steps = json.optJSONArray("steps");
                if (steps != null) {
                    for (int i = 0; i < steps.length(); i++) {
                        JSONObject step = steps.optJSONObject(i);
                        if (step == null) continue;
                        body.append("\n\n")
                            .append(step.optBoolean("passed") ? "PASSOU" : "FALHOU")
                            .append(" • ").append(step.optString("name"))
                            .append("\nFerramenta: ").append(step.optString("toolId"))
                            .append(" @ ").append(step.optString("toolVersion"))
                            .append("\nRun: ")
                            .append(step.optString("runId").isEmpty()
                                ? "nenhum" : step.optString("runId"))
                            .append("\nMotivo: ").append(step.optString("reason"))
                            .append("\nEntrada SHA-256: ")
                            .append(step.optString("inputSha256"))
                            .append("\nEsperado SHA-256: ")
                            .append(step.optString("expectedReturnSha256"))
                            .append("\nObtido SHA-256: ")
                            .append(step.optString("actualReturnSha256"))
                            .append("\nSaída SHA-256: ")
                            .append(step.optString("outputSha256"))
                            .append("\nDuração: ")
                            .append(step.optLong("durationMs")).append(" ms");
                    }
                }

                String details = body.toString();
                runOnUiThread(() -> {
                    if (!alive()) return;
                    TextView view = text(details, 13, FG, false);
                    view.setTypeface(Typeface.MONOSPACE);
                    view.setTextIsSelectable(true);
                    view.setPadding(dp(14), dp(12), dp(14), dp(12));
                    ScrollView scroll = new ScrollView(this);
                    scroll.addView(view);
                    new AlertDialog.Builder(this)
                        .setTitle("Relatório • IA de teste")
                        .setView(scroll)
                        .setPositiveButton("FECHAR", null)
                        .show();
                });
            } catch (Exception error) {
                runOnUiThread(() -> {
                    if (alive()) feedback.setText(
                        "Relatório indisponível: " + error.getMessage());
                });
            }
        });
    }

    private Button button(String label) {
        Button button = new Button(this);
        button.setText(label);
        button.setTextColor(FG);
        button.setTextSize(14);
        button.setBackgroundTintList(ColorStateList.valueOf(ACCENT));
        return button;
    }

    private TextView text(String value, int size, int color, boolean bold) {
        TextView view = new TextView(this);
        view.setText(value);
        view.setTextSize(size);
        view.setTextColor(color);
        if (bold) view.setTypeface(Typeface.DEFAULT, Typeface.BOLD);
        return view;
    }

    private LinearLayout.LayoutParams matchWrap() {
        return new LinearLayout.LayoutParams(
            ViewGroup.LayoutParams.MATCH_PARENT,
            ViewGroup.LayoutParams.WRAP_CONTENT);
    }

    private int dp(int value) {
        return Math.round(value * getResources().getDisplayMetrics().density);
    }

    private static String time(long epochMs) {
        if (epochMs <= 0) return "Data indisponível";
        return DateFormat.getDateTimeInstance(
            DateFormat.SHORT, DateFormat.SHORT,
            new Locale("pt", "BR")).format(new Date(epochMs));
    }

    private boolean alive() {
        return !isFinishing() && !isDestroyed();
    }

    @Override
    protected void onDestroy() {
        io.shutdownNow();
        super.onDestroy();
    }
}
